prefix p: <http://plantrdf-morethancode.rhcloud.com/schema#>

construct
{
	p:lastWatered rdfs:label 'Last watered'.
	$r p:lastWatered ?latest.
	?s ?_p1 ?_o1.
	?ipni ?_p2 ?_o2.
}
where
{
	$r a p:Plant.
	$r p:scientificName ?ipni.
	?s p:scientificName ?ipni.
	?s ?_p1 ?_o1.
	?ipni ?_p2 ?_o2.
	optional
	{
		select (max(?ts) as ?latest)
		where
		{
			?obs p:of $r.
			?obs p:on ?ts.
			?obs p:watered true.
		}
	}
}