prefix p: <http://plantrdf-morethancode.rhcloud.com/schema#>
prefix tn: <http://rs.tdwg.org/ontology/voc/TaxonName#>

construct
{
	p:lastWatered rdfs:label 'Last watered'.
	tn:genusPart rdfs:label 'Genus'.
	tn:specificEpithet rdfs:label 'Species'.
	tn:infraspecificEpithet rdfs:label 'Infraspecific'.
	$r p:lastWatered ?latest.
	$r ?_pr ?_or.
	?r ?_ps ?_os.
}
where
{
	graph $g
	{
		$r a p:Plant.
		$r ?_pr ?_or.
		$r p:scientificName ?ipni.
	}
	optional
	{
		graph ?_gs
		{
			?s p:scientificName ?ipni.
		}
		filter(?_gs != $g)
		?s ?_ps ?_os.
	}
	optional
	{
		select (max(?ts) as ?latest)
		where
		{
			?obs p:of $r.
			?obs p:on ?ts.
			?obs p:watered true.
		}
	}
}